---
- include_tasks: apt.yml
  when: ansible_os_family == "Debian"

- include_tasks: yum.yml
  when: ansible_os_family == "RedHat"

- name: Require local config
  lineinfile:
    dest: /etc/condor/condor_config
    line: 'REQUIRE_LOCAL_CONFIG_FILE = true'
    regexp: '^ *REQUIRE_LOCAL_CONFIG_FILE.*'
  notify: reload condor

- name: Copy local config
  template:
    src: condor_config.j2
    dest: /etc/condor/condor_config.local
    owner: root
    group: root
    mode: 0644
  notify: reload condor

#- name: condor walltime script
  #copy:
    #dest: /etc/condor/meta_walltime.py
    #src:  meta_walltime.py
    #mode: 0755
  #notify: reload condor

- name: Populate service facts
  service_facts:

- name: enable and start condor
  service:
    name: condor
    enabled: yes
    state: started
